/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CheckoutStatus = "completed" | "reversed";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type StockMovementKind = "adjustment" | "checkout" | "import" | "move_in" | "move_out" | "restock" | "reversal";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export type WinePhotoStatus = "pending" | "ready";

export interface CategoryOptions {
  createdAt: Generated<Timestamp>;
  fieldName: string;
  id: Generated<string>;
  value: string;
}

export interface CellarAccessSettings {
  bootstrapExpiresAt: Timestamp;
  bootstrapTokenHash: string;
  bootstrapUsedAt: Timestamp | null;
  id: number;
  ownerUserId: number | null;
}

export interface CellarImports {
  bottleCount: number;
  completedAt: Generated<Timestamp>;
  id: Generated<string>;
  imageCount: number;
  sourceName: string;
  sourceSha256: string;
  wineCount: number;
}

export interface CheckoutItems {
  checkoutId: string;
  id: Generated<string>;
  locationId: string;
  locationSnapshot: Json;
  quantity: number;
  wineId: string;
  wineSnapshot: Json;
}

export interface Checkouts {
  actorKey: string | null;
  createdAt: Generated<Timestamp>;
  dinnerLabel: string | null;
  guestName: string;
  id: Generated<string>;
  idempotencyKey: string;
  recipientsSnapshot: Generated<Json>;
  requestHash: string;
  reversedAt: Timestamp | null;
  reversedBy: string | null;
  status: Generated<CheckoutStatus>;
}

export interface Contacts {
  active: Generated<boolean>;
  createdAt: Generated<Timestamp>;
  displayName: string;
  id: Generated<string>;
  isHost: Generated<boolean>;
  phoneE164: string;
  version: Generated<Int8>;
}

export interface GuestLinks {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  revokedAt: Timestamp | null;
  tokenHash: string;
}

export interface GuestSessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  guestLinkId: string;
  id: string;
}

export interface InventoryOperations {
  actorKey: string;
  createdAt: Generated<Timestamp>;
  operationId: string;
  requestHash: string;
  result: Json;
}

export interface Locations {
  fridge: string;
  id: Generated<string>;
  shelf: string;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface StockMovements {
  actorName: string;
  checkoutId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  importId: string | null;
  kind: StockMovementKind;
  locationId: string;
  note: string | null;
  quantityDelta: number;
  wineId: string;
}

export interface TelegramDeliveries {
  checkoutId: string;
  createdAt: Generated<Timestamp>;
  event: string;
  guestName: string;
  id: string;
  partCount: number;
  recipientNames: Generated<Json>;
  state: string;
  updatedAt: Generated<Timestamp>;
}

export interface TelegramDeliveryParts {
  attemptCount: Generated<number>;
  content: string;
  createdAt: Generated<Timestamp>;
  deliveryId: string;
  errorCode: string | null;
  id: string;
  kind: string;
  partIndex: number;
  photoPath: string | null;
  sentAt: Timestamp | null;
  startedAt: Timestamp | null;
  state: string;
  updatedAt: Generated<Timestamp>;
}

export interface TelegramHostSettings {
  botUsername: string | null;
  createdAt: Generated<Timestamp>;
  hostChatId: string | null;
  id: number;
  nextSendAt: Timestamp | null;
  nonceExpiresAt: Timestamp | null;
  nonceHash: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface WinePhotos {
  actorKey: string;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  mimeType: string;
  operationId: string | null;
  photoPath: string;
  requestHash: string | null;
  sizeBytes: number;
  status: Generated<WinePhotoStatus>;
  storageKey: string;
}

export interface Wines {
  appellation: string | null;
  bottleSizeMl: number;
  colour: string | null;
  country: string | null;
  createdAt: Generated<Timestamp>;
  grapeBlend: string | null;
  id: Generated<string>;
  importId: string | null;
  photoPath: string | null;
  photoSha256: string | null;
  producer: string;
  region: string | null;
  sourceKey: string | null;
  subregion: string | null;
  sweetness: string | null;
  updatedAt: Generated<Timestamp>;
  version: Generated<Int8>;
  vintage: string | null;
  wineName: string;
  wineStyle: string | null;
}

export interface WineStock {
  locationId: string;
  quantity: number;
  updatedAt: Generated<Timestamp>;
  version: Generated<Int8>;
  wineId: string;
}

export interface DB {
  categoryOptions: CategoryOptions;
  cellarAccessSettings: CellarAccessSettings;
  cellarImports: CellarImports;
  checkoutItems: CheckoutItems;
  checkouts: Checkouts;
  contacts: Contacts;
  guestLinks: GuestLinks;
  guestSessions: GuestSessions;
  inventoryOperations: InventoryOperations;
  locations: Locations;
  loginAttempts: LoginAttempts;
  sessions: Sessions;
  stockMovements: StockMovements;
  telegramDeliveries: TelegramDeliveries;
  telegramDeliveryParts: TelegramDeliveryParts;
  telegramHostSettings: TelegramHostSettings;
  userPasswords: UserPasswords;
  users: Users;
  winePhotos: WinePhotos;
  wines: Wines;
  wineStock: WineStock;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
export const StockMovementKindArrayValues: [StockMovementKind, ...StockMovementKind[]] = ["adjustment","checkout","import","move_in","move_out","restock","reversal"];
export const CheckoutStatusArrayValues: [CheckoutStatus, ...CheckoutStatus[]] = ["completed","reversed"];
export const WinePhotoStatusArrayValues: [WinePhotoStatus, ...WinePhotoStatus[]] = ["pending","ready"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
